[workspace]
members = ["crates/*", "examples", "tools"]
resolver = "3"

[workspace.package]
authors = ["Christian Balcom <robot.inventor@gmail.com>"]
repository = "https://github.com/computer-whisperer/damascene"
homepage = "https://github.com/computer-whisperer/damascene"
edition = "2024"
rust-version = "1.85"
